# Generated by Django 2.2.5 on 2021-03-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, choices=[('All upper', 'All upper'), ('All lower', 'All lower'), ('Capitalize first only', 'Capitalize first only')], max_length=20)),
                ('input', models.TextField(blank=True)),
                ('output', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FindModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, choices=[('Case Sensitive', 'Case Sensitive'), ('Case invariant', 'Case invariant')], max_length=20)),
                ('word_to_find', models.CharField(blank=True, max_length=100)),
                ('paragraph', models.TextField(blank=True)),
                ('occurances', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WordsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, choices=[('With Spaces', 'With Spaces'), ('Without Spaces', 'Without Spaces'), ('Characteres', 'Characteres'), ('Words', 'Words'), ('Sentences', 'Sentences')], max_length=20)),
                ('text', models.TextField(blank=True)),
                ('result', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
