# Generated by Django 2.2.5 on 2021-03-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Counter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changemodel',
            old_name='method',
            new_name='method2',
        ),
        migrations.RenameField(
            model_name='findmodel',
            old_name='method',
            new_name='method3',
        ),
    ]
